name: 'Update docker-compose.yml'
description: 'Update image version in docker-compose.yml, build and push image'

inputs:
  image:
    description: 'Name of image in docker-compose.yml'
    required: true
  docker-file:
    description: 'Path to docker file to build'
    required: true
    default: 'Dockerfile'
  rebuild-if-changed:
    description: 'List of files to hash'
    required: true
  registry:
    description: 'Server address of container registry'
    required: true
    default: "docker.io"
  registry-user:
    description: 'User name for container registry'
    required: true
  registry-pass:
    description: 'Password for container registry'
    required: true
  working-directory:
    description: 'Working directory'
    required: true
    default: "."

outputs:
  image-tag:
    description: "Image and tag"
    value: ${{ steps.get-tag.outputs.tag }}
  updated:
    description: "Whether image needed to be built"
    value: ${{ steps.check-need-build.outputs.need-build }}

runs:
  using: "composite"
  steps:
    - name: Get current image and tag name
      id: get-tag
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        set -x
        python ${{ github.action_path }}/get_tag.py ${{ inputs.image }} ${{ inputs.rebuild-if-changed }}

    - name: Check if we need to rebuild
      id: check-need-build
      shell: bash
      run: |
        set -x
        RETURN_CODE=`docker manifest inspect ${{ steps.get-tag.outputs.tag }} > /dev/null && echo $? || echo $?`
        echo "::set-output name=need-build::$RETURN_CODE"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-pass }}

    - name: Update image tag in git
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        set -x

        ARGS="--platform linux/amd64,linux/arm64 -t ${{ steps.get-tag.outputs.tag }} -f ${{ inputs.docker-file }} ."

        # build docker image
        if [ "${{ steps.check-need-build.outputs.need-build }}" = "1" ]; then
          docker buildx build --output "type=image,push=false" ${ARGS}
        
          if [ "${{ github.event_name }}" = "push" ]; then
            # push
            docker buildx build --output "type=image,push=true" ${ARGS}
            # avoid leaving docker login on disk for tasks that don't have access to secrets
            docker logout "${{ inputs.registry }}"
          fi
        fi

